apiVersion: v1
kind: Template
metadata:
  name: matterbridge-plus
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    description: "S2I builder image for Go1.6"
        name: "s2i-go"
      spec:
        dockerImageRepository: "goern/go-16-centos7"
      tags:
        - name: "latest"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      git:
        uri: https://github.com/goern/mattermost-openshift
        ref: "centos7"
      type: Git
      contextDir: matterbridge-plus
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: go-16-centos7:latest
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    selector:
      name: ${APPLICATION_NAME}
    replicas: 1
    template:
      metadata:
        labels:
          name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}
parameters:
- name: APPLICATION_NAME
  required: true
  value: matterbridge-plus
- name: MATTERMOST_HOST
  required: false
  from: '[a-zA-Z0-9]{16}'
  generate: expression
- name: MATTERMOST_PORT
  required: false
  value: 8065
- name: MATTERMOST_BOT_USERNAME
  required: false
  value: matterbot
  from: '[a-zA-Z0-9]{16}'
  generate: expression
- name: MATTERMOST_BOT_PASSWORD
  required: false
